"""
Shelf Life Estimator — SQLAlchemy ORM Models
=============================================
Database table definitions for the application.
"""

from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.database import Base


class FoodItem(Base):
    """
    Reference table of all known food items with shelf life data.

    Each food item has baseline shelf life values for different
    storage methods (room temperature, refrigerator, freezer)
    and curated storage tips.
    """

    __tablename__ = "food_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    name: Mapped[str] = mapped_column(String(100), unique=True, nullable=False, index=True)
    category: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    shelf_life_room_temp_days: Mapped[float] = mapped_column(Float, nullable=False)
    shelf_life_fridge_days: Mapped[float] = mapped_column(Float, nullable=False)
    shelf_life_freezer_days: Mapped[float] = mapped_column(Float, nullable=False)
    storage_tips: Mapped[str] = mapped_column(Text, nullable=True)
    image_url: Mapped[str | None] = mapped_column(String(500), nullable=True)

    # Relationship
    inventory_items: Mapped[list["UserInventory"]] = relationship(
        back_populates="food_item", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<FoodItem(id={self.id}, name='{self.name}', category='{self.category}')>"


class User(Base):
    """
    User accounts for the application.

    Stores basic auth info. Can be expanded later with
    profile data, preferences, etc.
    """

    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    username: Mapped[str] = mapped_column(String(50), unique=True, nullable=False, index=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationship
    inventory_items: Mapped[list["UserInventory"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<User(id={self.id}, username='{self.username}')>"


class UserInventory(Base):
    """
    Tracks food items scanned/added by a user.

    Each record represents one food item the user is tracking,
    with its freshness score, storage method, and estimated expiry.
    """

    __tablename__ = "user_inventory"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    food_item_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("food_items.id", ondelete="CASCADE"), nullable=False
    )
    freshness_score: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    storage_method: Mapped[str] = mapped_column(
        String(20), nullable=False, default="room_temp"
    )  # room_temp, fridge, freezer
    estimated_days_remaining: Mapped[float] = mapped_column(Float, nullable=False)
    scanned_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    estimated_expiry: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    is_expired: Mapped[bool] = mapped_column(Boolean, default=False)
    is_consumed: Mapped[bool] = mapped_column(Boolean, default=False)
    image_path: Mapped[str | None] = mapped_column(String(500), nullable=True)
    quantity: Mapped[int] = mapped_column(Integer, default=1)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Relationships
    user: Mapped["User"] = relationship(back_populates="inventory_items")
    food_item: Mapped["FoodItem"] = relationship(back_populates="inventory_items")
    notifications: Mapped[list["Notification"]] = relationship(
        back_populates="inventory_item", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return (
            f"<UserInventory(id={self.id}, food='{self.food_item_id}', "
            f"days_remaining={self.estimated_days_remaining})>"
        )


class Notification(Base):
    """
    Expiry alert notifications for inventory items.

    Generated by the background scheduler when food items
    are approaching their estimated expiry date.
    """

    __tablename__ = "notifications"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    inventory_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("user_inventory.id", ondelete="CASCADE"), nullable=False
    )
    message: Mapped[str] = mapped_column(String(500), nullable=False)
    notify_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    sent: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationship
    inventory_item: Mapped["UserInventory"] = relationship(back_populates="notifications")

    def __repr__(self) -> str:
        return f"<Notification(id={self.id}, sent={self.sent})>"
