# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHFhbZXi_vMLe8R-ZLYMj5PRhO-tI7Mz
"""

from google.colab import drive

drive.mount('/content/drive')

import os
print(os.listdir('/content/drive/MyDrive/DataSet 1/fruits-360-3-body-problem/Training'))

import os
dataset_path = ("/content/drive/MyDrive/DataSet 1/fruits-360-3-body-problem/Training")


class_names = sorted(os.listdir(dataset_path))
print(f"Found {len(class_names)} fruit classes:")
print(class_names)

IMG_SIZE    = 224
BATCH_SIZE  = 32
NUM_CLASSES = len(class_names)


EPOCHS_HEAD    = 10
EPOCHS_FINETUNE = 15
LEARNING_RATE  = 0.001
FINETUNE_LR    = 0.0001


MODEL_SAVE_PATH = "/content/drive/MyDrive/fresco_classifier.h5"
LABELS_SAVE_PATH = "/content/drive/MyDrive/fresco_labels.txt"

print(f"Training on {NUM_CLASSES} classes")
print(f"Image size: {IMG_SIZE}x{IMG_SIZE}")
print(f"Batch size: {BATCH_SIZE}")

import tensorflow as tf


full_dataset = tf.keras.utils.image_dataset_from_directory(
    dataset_path,
    labels='inferred',
    label_mode='categorical',
    class_names=class_names,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=42,
)


total_batches = tf.data.experimental.cardinality(full_dataset).numpy()
print(f"Total batches: {total_batches}")


train_size = int(0.8 * total_batches)
val_size   = int(0.1 * total_batches)
test_size  = total_batches - train_size - val_size

train_ds = full_dataset.take(train_size)
val_ds   = full_dataset.skip(train_size).take(val_size)
test_ds  = full_dataset.skip(train_size + val_size)

print(f"Train batches: {train_size}")
print(f"Val batches:   {val_size}")
print(f"Test batches:  {test_size}")

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(12, 8))

for images, labels in train_ds.take(1):
    for i in range(min(12, BATCH_SIZE)):
        ax = plt.subplot(3, 4, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        label_index = np.argmax(labels[i])
        plt.title(class_names[label_index], fontsize=10)
        plt.axis("off")

plt.suptitle("Sample Training Images", fontsize=14)
plt.tight_layout()
plt.show()

from tensorflow.keras import layers


data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.15),
    layers.RandomZoom(0.1),
    layers.RandomBrightness(0.1),
    layers.RandomContrast(0.1),
], name="augmentation")

preprocess_input = tf.keras.applications.mobilenet_v2.preprocess_input


AUTOTUNE = tf.data.AUTOTUNE

train_ds = (
    train_ds
    .map(lambda x, y: (data_augmentation(x, training=True), y))
    .map(lambda x, y: (preprocess_input(x), y))
    .cache()
    .prefetch(AUTOTUNE)
)

val_ds = (
    val_ds
    .map(lambda x, y: (preprocess_input(x), y))
    .cache()
    .prefetch(AUTOTUNE)
)

test_ds = (
    test_ds
    .map(lambda x, y: (preprocess_input(x), y))
    .prefetch(AUTOTUNE)
)

print("Augmentation and preprocessing pipeline ready")

from tensorflow.keras import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.applications import MobileNetV2


base_model = MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights='imagenet'
)


base_model.trainable = False


inputs  = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x       = base_model(inputs, training=False)

x       = GlobalAveragePooling2D()(x)

x       = Dense(256, activation='relu')(x)

x       = Dropout(0.3)(x)

outputs = Dense(NUM_CLASSES, activation='softmax')(x)


model = Model(inputs, outputs)


print(f"Total parameters:     {model.count_params():,}")
print(f"Trainable parameters: {sum([tf.size(w).numpy() for w in model.trainable_weights]):,}")
print("(Only your new head layers are trainable in Phase 1)")

from tensorflow.keras.callbacks import (
    EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
)


model.compile(
    optimizer=tf.keras.optimizers.Adam(LEARNING_RATE),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_phase1 = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=3,
        restore_best_weights=True
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=2,
        min_lr=1e-7
    ),
]

print("── Phase 1: Training classification head ──")
print(f"Frozen base layers: {len(base_model.layers)}")
print(f"Training for up to {EPOCHS_HEAD} epochs...")

history_phase1 = model.fit(
    train_ds,
    epochs=EPOCHS_HEAD,
    validation_data=val_ds,
    callbacks=callbacks_phase1,
    verbose=1
)

print(f"\nPhase 1 complete")
print(f"Best val accuracy: {max(history_phase1.history['val_accuracy']):.2%}")

import os
classes = sorted(os.listdir("/content/drive/MyDrive/DataSet 1/fruits-360-3-body-problem/Training"))
print(f"{len(classes)} classes:")
print(classes)