"""
Shelf Life Estimator — Seed Data
==================================
Pre-populates the database with 40+ fruits, each with:
  - Shelf life data for 3 storage methods
  - Subcategory classification
  - Ethylene production/sensitivity flags
  - Optimal storage temperature range
  - Ripeness indicators
  - Curated storage tips

Run on first startup if the fruits table is empty.
"""

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.schema import Fruit, User


# ============================================
# 40+ Fruits with Full Attribute Data
# ============================================
# Using a list of dicts instead of tuples for readability
# and to accommodate the expanded attribute set.

FRUIT_DATA = [
    # === COMMON FRUITS ===
    {
        "name": "Apple",
        "subcategory": "common",
        "shelf_life_room_temp_days": 7,
        "shelf_life_fridge_days": 28,
        "shelf_life_freezer_days": 240,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 1.0,
        "optimal_temp_max": 4.0,
        "ripeness_indicator": "Firm, bright color, no soft spots. Smells sweet at the stem.",
        "storage_tips": "Store loose in the fridge crisper drawer. Keep away from other fruits as apples produce ethylene gas that ripens others faster.",
    },
    {
        "name": "Banana",
        "subcategory": "common",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 13.0,
        "optimal_temp_max": 15.0,
        "ripeness_indicator": "Yellow skin with small brown spots = perfectly ripe. Green = unripe. Brown = overripe but great for baking.",
        "storage_tips": "Store at room temperature until ripe. Refrigerate only when ripe — skin darkens but flesh stays fresh longer. Freeze peeled for smoothies.",
    },
    {
        "name": "Grape",
        "subcategory": "common",
        "shelf_life_room_temp_days": 2,
        "shelf_life_fridge_days": 10,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Firm, plump, attached to green stems. Wrinkled or brown stems = old.",
        "storage_tips": "Store unwashed in a perforated bag in the fridge. Remove spoiled grapes immediately to prevent spread.",
    },
    {
        "name": "Avocado",
        "subcategory": "common",
        "shelf_life_room_temp_days": 4,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 120,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 7.0,
        "optimal_temp_max": 13.0,
        "ripeness_indicator": "Gives slightly to gentle pressure. Dark green/brown skin. Peek under stem — green = good, brown = overripe.",
        "storage_tips": "Ripen at room temperature. Once ripe, refrigerate to extend life by 2-3 days. Sprinkle cut avocado with lemon juice to prevent browning.",
    },
    {
        "name": "Watermelon",
        "subcategory": "common",
        "shelf_life_room_temp_days": 7,
        "shelf_life_fridge_days": 14,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 10.0,
        "optimal_temp_max": 15.0,
        "ripeness_indicator": "Yellow spot on bottom (where it rested on ground). Hollow sound when tapped. Heavy for its size.",
        "storage_tips": "Whole watermelon keeps at room temperature. Once cut, wrap tightly and refrigerate. Freeze cubes for smoothies and snacks.",
    },

    # === CITRUS FRUITS ===
    {
        "name": "Orange",
        "subcategory": "citrus",
        "shelf_life_room_temp_days": 10,
        "shelf_life_fridge_days": 21,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 3.0,
        "optimal_temp_max": 8.0,
        "ripeness_indicator": "Heavy for its size, firm skin, bright color. Orange color doesn't always mean ripe — weight matters more.",
        "storage_tips": "Room temperature for a week, fridge for longer storage. Store in mesh bag for air circulation. Don't stack too tightly.",
    },
    {
        "name": "Lemon",
        "subcategory": "citrus",
        "shelf_life_room_temp_days": 7,
        "shelf_life_fridge_days": 28,
        "shelf_life_freezer_days": 90,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 4.0,
        "optimal_temp_max": 10.0,
        "ripeness_indicator": "Bright yellow, firm, heavy for its size. Thin-skinned lemons have more juice.",
        "storage_tips": "Store whole lemons in the fridge in a sealed bag for up to a month. Room temp is fine for a week. Roll before juicing for more juice.",
    },
    {
        "name": "Lime",
        "subcategory": "citrus",
        "shelf_life_room_temp_days": 7,
        "shelf_life_fridge_days": 21,
        "shelf_life_freezer_days": 90,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 4.0,
        "optimal_temp_max": 10.0,
        "ripeness_indicator": "Bright green, firm, heavy for its size. Slight yellow tinge = extra ripe and juicy.",
        "storage_tips": "Similar to lemons. Keep in a sealed bag in the fridge. Limes dry out faster than lemons, so bag storage is key.",
    },
    {
        "name": "Grapefruit",
        "subcategory": "citrus",
        "shelf_life_room_temp_days": 7,
        "shelf_life_fridge_days": 21,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 4.0,
        "optimal_temp_max": 10.0,
        "ripeness_indicator": "Heavy for its size = more juice. Slightly flat on top and bottom. Smooth, thin skin.",
        "storage_tips": "Store at room temp for a week or fridge for longer. Heavier grapefruits have more juice. Peel segments for easy snacking.",
    },
    {
        "name": "Tangerine",
        "subcategory": "citrus",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 14,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 4.0,
        "optimal_temp_max": 8.0,
        "ripeness_indicator": "Bright orange, slightly loose skin, sweet citrus aroma. Heavy = juicy.",
        "storage_tips": "Store loose in the fridge. Easy to peel and segment. Eat within a week for best flavor. Keep away from strong odors.",
    },
    {
        "name": "Clementine",
        "subcategory": "citrus",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 14,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 4.0,
        "optimal_temp_max": 8.0,
        "ripeness_indicator": "Bright orange, smooth glossy skin, feels heavy. Should be seedless.",
        "storage_tips": "Refrigerate in a mesh bag or loose in the crisper. Don't store in sealed plastic — moisture causes mold.",
    },

    # === BERRIES ===
    {
        "name": "Strawberry",
        "subcategory": "berries",
        "shelf_life_room_temp_days": 2,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Bright red all over, fresh green caps, firm. White or green tips = picked too early.",
        "storage_tips": "Don't wash until ready to eat. Store in a single layer with paper towel to absorb moisture. Remove any moldy ones immediately.",
    },
    {
        "name": "Blueberry",
        "subcategory": "berries",
        "shelf_life_room_temp_days": 1,
        "shelf_life_fridge_days": 10,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Deep blue-purple, firm, silvery bloom (frosty coating) = fresh. Wrinkled or leaking = old.",
        "storage_tips": "Don't wash until ready to eat. Store in original container in the fridge. Discard any moldy berries immediately — mold spreads fast.",
    },
    {
        "name": "Raspberry",
        "subcategory": "berries",
        "shelf_life_room_temp_days": 1,
        "shelf_life_fridge_days": 5,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Deep red, plump, no mold. Should pull easily from the stem. Leaking juice = overripe.",
        "storage_tips": "Extremely delicate. Don't wash until eating. Store in a single layer on paper towel. Use within 2-3 days of purchase.",
    },
    {
        "name": "Blackberry",
        "subcategory": "berries",
        "shelf_life_room_temp_days": 1,
        "shelf_life_fridge_days": 5,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Deep black, plump, firm. Red drupelets = not fully ripe. Leaking = use immediately.",
        "storage_tips": "Similar to raspberries — very perishable. Store unwashed in a single layer. A vinegar rinse (1:3 vinegar to water) before storing extends life.",
    },
    {
        "name": "Cranberry",
        "subcategory": "berries",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 28,
        "shelf_life_freezer_days": 270,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 2.0,
        "optimal_temp_max": 4.0,
        "ripeness_indicator": "Firm, deep red, bounces when dropped. Soft or wrinkled = old.",
        "storage_tips": "Fresh cranberries last surprisingly long in the fridge. Freeze in original bag. Bounce test: fresh cranberries bounce!",
    },

    # === TROPICAL FRUITS ===
    {
        "name": "Mango",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 10,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 10.0,
        "optimal_temp_max": 13.0,
        "ripeness_indicator": "Gives slightly to pressure, sweet aroma at stem end. Color is NOT a reliable indicator — smell and touch matter.",
        "storage_tips": "Ripen at room temperature. Once ripe (slightly soft, fragrant), refrigerate to slow further ripening. Peel and cube before freezing.",
    },
    {
        "name": "Pineapple",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 7.0,
        "optimal_temp_max": 13.0,
        "ripeness_indicator": "Sweet smell at base, golden color, leaves pull out easily. Heavy for size = juicy.",
        "storage_tips": "Cut pineapple should be refrigerated in an airtight container. Whole pineapple keeps at room temp for a few days. Smell the base — sweet = ripe.",
    },
    {
        "name": "Papaya",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 7.0,
        "optimal_temp_max": 13.0,
        "ripeness_indicator": "Skin mostly yellow, gives to gentle pressure, sweet aroma.",
        "storage_tips": "Ripen at room temperature until skin is mostly yellow. Once ripe, refrigerate. Cut papaya lasts 2-3 days in the fridge.",
    },
    {
        "name": "Kiwi",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 14,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Gives slightly to pressure. Hard = unripe. Very soft = overripe.",
        "storage_tips": "Firm kiwis ripen at room temp in 3-5 days. Place near bananas or apples to speed ripening. Refrigerate once ripe.",
    },
    {
        "name": "Passion Fruit",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 14,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 7.0,
        "optimal_temp_max": 10.0,
        "ripeness_indicator": "Wrinkled, dark purple skin = ripe. Smooth skin = not ready yet.",
        "storage_tips": "Ripe when skin is wrinkled and dark purple. Store at room temp until wrinkled, then refrigerate. Scoop out pulp and freeze.",
    },
    {
        "name": "Dragon Fruit",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 120,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 7.0,
        "optimal_temp_max": 10.0,
        "ripeness_indicator": "Bright pink skin, gives slightly. Dried-out or brown = old.",
        "storage_tips": "Store at room temperature for a few days. Refrigerate in a bag once cut. Bright pink skin should give slightly when ripe.",
    },
    {
        "name": "Guava",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 8.0,
        "optimal_temp_max": 10.0,
        "ripeness_indicator": "Slightly soft, fragrant, light green to yellow skin.",
        "storage_tips": "Ripen at room temperature. Once fragrant and slightly soft, refrigerate. Green guavas are unripe but still edible.",
    },
    {
        "name": "Lychee",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 2,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 1.0,
        "optimal_temp_max": 4.0,
        "ripeness_indicator": "Red/pink bumpy shell, sweet aroma. Brown shell doesn't always mean bad — check the flesh.",
        "storage_tips": "Highly perishable. Refrigerate immediately in a perforated bag. Skin turns brown in the fridge but flesh stays good.",
    },
    {
        "name": "Coconut",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 14,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 4.0,
        "ripeness_indicator": "Heavy with lots of water inside (shake to hear). No cracks, no mold around eyes.",
        "storage_tips": "Whole unopened coconut lasts 2 weeks at room temp. Once opened, refrigerate the meat and use within a week. Freeze shredded.",
    },
    {
        "name": "Pomegranate",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 7,
        "shelf_life_fridge_days": 30,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 5.0,
        "optimal_temp_max": 7.0,
        "ripeness_indicator": "Heavy for its size, angular shape (not round), deep red skin. Scratch the skin — should be red underneath.",
        "storage_tips": "Whole pomegranates last weeks in the fridge. Seeds (arils) in a container last about a week refrigerated. Freeze arils flat on a tray.",
    },
    {
        "name": "Star Fruit",
        "subcategory": "tropical",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 120,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 5.0,
        "optimal_temp_max": 10.0,
        "ripeness_indicator": "Bright yellow, edges slightly brown. Green = unripe but edible.",
        "storage_tips": "Ripen at room temperature until edges turn brown. Store ripe fruit in the fridge. Slice crosswise for decorative star shapes.",
    },

    # === STONE FRUITS ===
    {
        "name": "Peach",
        "subcategory": "stone",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Gives to gentle pressure near stem, sweet fragrance. Hard = unripe.",
        "storage_tips": "Ripen on counter in a paper bag. Refrigerate once slightly soft near the stem. Bruises easily — handle with care.",
    },
    {
        "name": "Pear",
        "subcategory": "stone",
        "shelf_life_room_temp_days": 4,
        "shelf_life_fridge_days": 10,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Check the neck — press gently near the stem. If it gives, it's ripe. Pears ripen from inside out.",
        "storage_tips": "Ripen at room temperature. Check daily — pears ripen from the inside out. Refrigerate when slightly soft near the stem.",
    },
    {
        "name": "Plum",
        "subcategory": "stone",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Gives slightly to pressure, powdery bloom on skin. Very soft or wrinkled = overripe.",
        "storage_tips": "Ripen at room temperature. Once they give slightly to pressure, move to fridge. Great for baking and preserves.",
    },
    {
        "name": "Cherry",
        "subcategory": "stone",
        "shelf_life_room_temp_days": 1,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Deep red/mahogany, firm, green stems. Soft or brown = past prime.",
        "storage_tips": "Highly perishable. Refrigerate immediately in a bag with a paper towel. Don't wash until ready to eat. Leave stems on for longer life.",
    },
    {
        "name": "Apricot",
        "subcategory": "stone",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Golden orange, slightly soft, sweet aroma. Hard and pale = unripe.",
        "storage_tips": "Ripen at room temperature. Very soft apricots should be eaten immediately. Store in a single layer to prevent bruising.",
    },
    {
        "name": "Nectarine",
        "subcategory": "stone",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Gives to gentle pressure, sweet smell, no green coloring. Similar to peach but smooth skin.",
        "storage_tips": "Similar to peaches but with smooth skin. Ripen on counter, refrigerate when ripe. Don't stack — they bruise easily.",
    },

    # === MELONS ===
    {
        "name": "Cantaloupe",
        "subcategory": "melons",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 10,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 2.0,
        "optimal_temp_max": 5.0,
        "ripeness_indicator": "Sweet smell at stem end, yields to pressure, tan netting pattern. Smooth stem end = fell off vine naturally (good).",
        "storage_tips": "Whole cantaloupe at room temp until ripe (fragrant, yields to pressure at stem end). Once cut, refrigerate and use within 3 days.",
    },
    {
        "name": "Honeydew",
        "subcategory": "melons",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 10,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 7.0,
        "optimal_temp_max": 10.0,
        "ripeness_indicator": "Creamy yellow skin (not green), waxy feel, sweet smell. Heavy for its size.",
        "storage_tips": "Store at room temp until ripe. Ripe honeydew has creamy yellow skin and a sweet smell. Refrigerate once cut.",
    },

    # === OTHER FRUITS ===
    {
        "name": "Fig",
        "subcategory": "other",
        "shelf_life_room_temp_days": 2,
        "shelf_life_fridge_days": 5,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Soft, drooping stem, sweet fragrance. Should yield to gentle pressure. Hard or cracked = no good.",
        "storage_tips": "Very perishable. Refrigerate immediately. Handle gently — figs bruise at the slightest touch. Store in a single layer.",
    },
    {
        "name": "Date",
        "subcategory": "other",
        "shelf_life_room_temp_days": 30,
        "shelf_life_fridge_days": 180,
        "shelf_life_freezer_days": 365,
        "is_ethylene_producer": False,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 4.0,
        "ripeness_indicator": "Plump, glossy, brown/amber color. Dry or crystallized = still edible but past peak.",
        "storage_tips": "Dried dates last months at room temp. Fresh dates should be refrigerated. Store in an airtight container. Freeze for years.",
    },
    {
        "name": "Persimmon",
        "subcategory": "other",
        "shelf_life_room_temp_days": 5,
        "shelf_life_fridge_days": 14,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": True,
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "ripeness_indicator": "Fuyu type: eat when firm. Hachiya type: wait until completely soft/translucent.",
        "storage_tips": "Fuyu (firm) type can be eaten crisp. Hachiya type must be fully soft/ripe. Ripen at room temp, refrigerate when ready.",
    },
    {
        "name": "Jackfruit",
        "subcategory": "other",
        "shelf_life_room_temp_days": 3,
        "shelf_life_fridge_days": 7,
        "shelf_life_freezer_days": 60,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 13.0,
        "optimal_temp_max": 16.0,
        "ripeness_indicator": "Strong sweet smell, yields to pressure, spikes flatten slightly.",
        "storage_tips": "Whole jackfruit keeps at room temp for a few days. Cut sections should be refrigerated in airtight containers.",
    },
    {
        "name": "Plantain",
        "subcategory": "other",
        "shelf_life_room_temp_days": 7,
        "shelf_life_fridge_days": 10,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 13.0,
        "optimal_temp_max": 15.0,
        "ripeness_indicator": "Green = starchy (for frying). Yellow = sweeter. Black = very sweet (for baking). ALL are cooked before eating.",
        "storage_tips": "Cook before eating (unlike bananas). Green = starchy, Yellow = sweeter, Black = very sweet. Ripen at room temperature.",
    },
    {
        "name": "Soursop",
        "subcategory": "other",
        "shelf_life_room_temp_days": 2,
        "shelf_life_fridge_days": 5,
        "shelf_life_freezer_days": 180,
        "is_ethylene_producer": True,
        "is_ethylene_sensitive": False,
        "optimal_temp_min": 13.0,
        "optimal_temp_max": 16.0,
        "ripeness_indicator": "Gives to pressure, dark green skin, strong sweet-sour aroma.",
        "storage_tips": "Ripen at room temperature until soft. Once ripe, eat immediately or scoop out pulp and freeze. Very perishable when ripe.",
    },
]


# Default user for single-user mode
DEFAULT_USER = {
    "username": "default",
    "email": "user@shelflife.local",
    "password_hash": "$2b$12$placeholder_hash_for_default_user",
}


async def seed_database(db: AsyncSession) -> None:
    """
    Populate the database with fruits and a default user.
    Only runs if the tables are empty.
    """
    # Check if fruits already exist
    result = await db.execute(select(func.count()).select_from(Fruit))
    count = result.scalar()

    if count > 0:
        print(f"✅ Database already seeded with {count} fruits. Skipping.")
        return

    print("🌱 Seeding database with fruits...")

    # Seed fruits from the data list
    fruits = [Fruit(**data) for data in FRUIT_DATA]

    db.add_all(fruits)

    # Seed default user
    result = await db.execute(select(func.count()).select_from(User))
    user_count = result.scalar()

    if user_count == 0:
        default_user = User(**DEFAULT_USER)
        db.add(default_user)
        print("👤 Created default user")

    await db.commit()
    print(f"✅ Seeded {len(fruits)} fruits!")
